### ISSUE TITLE
hey KaustubhPatange 

### ISSUE THREAD

**Issue by omgbox** [KaustubhPatange/Moviesy#27]
Mr KaustubhPatange,  come on man you know this is bullshit,  many free software can do everything what you charging for. 

just one of many **stremio apk**, **_Amnis_** apps which are free and Chromecast support with subtitles. 

this is not the correct way of earning honest money as a developer. go to Fiverr - Freelance Services Marketplace and earn honest money. 

many free apk which stream torrents on android https://github.com/AndroidTorrent
![Untitled](https://user-images.githubusercontent.com/11356775/126884456-edbb1c3b-cd93-4d32-896f-0635d2754884.png)

![Untitled](https://user-images.githubusercontent.com/11356775/126884599-07a6596f-7fba-4025-a79d-58be80912d91.png)

**Comment by KaustubhPatange** [comment]
If you have so much problem with the app why don't uninstall the app and call it off a day. So unprofessional to just make a rant!

For the record I am using thr Torrent stream Android project you mentioned which does not support seekbar changes!

Closing this issue because it's not an issue it's yout opinion.
