### ISSUE TITLE
Pro version without google account

### ISSUE THREAD

**Issue by Sinasta** [KaustubhPatange/Moviesy#30]
Thanks for your work. I would like to know if there is a way of buying the pro version without having a google account? Thank you!

**Comment by KaustubhPatange** [comment]
As much I hate to say but it is the only way I can identify valid users. Using Google sign-in through a google account can ensure that the account you are using is valid which then can be used as an `id` to know whether there is pro membership associated with it or not (This is what is stored in my sever).

The problem with having an input field where you can enter "license key" could be risky because duplicate premium verification can be created (i.e 1 license key but multiple users using pro version) & there is no way to detect who is the real one & who are the fake users. That's why Google sign-in is used. 

I'm sorry I can't do anything but this is needed to ensure everything works fine :(

**Comment by Sinasta** [comment]
i understand. Isn't it possible to publish another app in the playstore which then can link to the google account? i dont really feel comfortable to link my account with Moviesy. With an external app i wouldn't mind.

**Comment by KaustubhPatange** [comment]
The app is not available on the Google Play because they don't allow such apps. BTW, there is no risk when you sign in with Google account, I'm not violating any of your privacy to anyone that is the reason why the app is open-sourced so that users can see that I'm not doing something I'm not supposed to do. 

When you sign in, I only get information about your email id, that's it nothing more is provided by Google. They respect your privacy & that's why they only provide email id to me! None of your data is shared by them with me. So, there is no risk in signing with a Google account :)

**Comment by Sinasta** [comment]
Thanks for your answer. I am actually less afraid of the information you get as the developer but more about that google knows that i am using moviesy.

**Comment by KaustubhPatange** [comment]
No, they don't! 

There is no kind of Google Play service integrated into the app which lets them know that you are using Moviesy. All they know is that at this time you sign in with this account somewhere (they only know about the API, not the app where you've signed into). So simple answer, they don't know about Moviesy at all.

**Comment by Sinasta** [comment]
Ok Great! My last question is, do you think about Series integration?

**Comment by KaustubhPatange** [comment]
Currently there are not any plans for adding TV Shows but in future I'll take a look into it.

**Comment by Sinasta** [comment]
that would be awesome. Thank you!

**Comment by KaustubhPatange** [comment]
Closing this issue!
